# Generated by Django 5.0.4 on 2024-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_of_publish', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=13)),
                ('image_url', models.URLField(max_length=2000)),
            ],
        ),
    ]
