# Generated by Django 5.0.4 on 2024-05-20 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_usertype_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usertype',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.usertype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.usertype'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.BooleanField(default=False),
        ),
    ]
