# Generated by Django 5.0.4 on 2024-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_profile_usertype_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publish',
            field=models.DateField(),
        ),
    ]
