# Generated by Django 5.0.6 on 2024-06-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_book_year_of_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
